import {test,expect} from '@playwright/test';
import path from 'node:path';
import {readFileSync} from 'node:fs';
const url=process.env.UI_URL||'http://127.0.0.1:5173';
test('sample review resolves an item, remembers correction, approves and exports',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/?preview=1');await expect(page.getByRole('heading',{name:'Your invoice worklist.'})).toBeVisible();
 await expect(page.locator('tbody tr')).toHaveCount(7);
 await page.screenshot({path:'test-results/worklist-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Review INV-2026-0081'}).click();
 await expect(page.getByRole('heading',{name:'INV-2026-0081'})).toBeVisible();
 await expect(page.getByText('Resolve every item to an RMS item ID')).toBeVisible();
 await page.getByRole('button',{name:/Resolve item/}).click();
 await page.getByRole('button',{name:'Confirm this item'}).first().click();
 await page.getByRole('button',{name:'Save changes'}).click();
 await expect(page.getByText('Amounts and item mappings reconcile')).toBeVisible();
 await page.getByRole('button',{name:'Approve invoice',exact:true}).click();
 await page.getByRole('button',{name:'Confirm review & approve'}).click();
 await expect(page.getByRole('button',{name:'Approved',exact:true})).toBeDisabled();
 await page.screenshot({path:'test-results/review-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'All invoices',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select INV-2026-0081',exact:true}).check();
 await page.getByRole('button',{name:'Select all approved matching search'}).click();
 await expect(page.locator('.selection-bar')).toContainText('4 selected');
 await page.getByRole('button',{name:'Clear',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select INV-2026-0081',exact:true}).check();
 await page.getByRole('button',{name:'Export selected'}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download sample JSON'}).click();
 expect((await download).suggestedFilename()).toBe('sample-invoice-review.json');
 await page.getByRole('button',{name:'Learned matches',exact:true}).click();await expect(page.getByRole('cell',{name:'LUM HYDR SERUM 30 ML',exact:true})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'Learned matches',exact:true}).click();await expect(page.getByRole('cell',{name:'LUM HYDR SERUM 30 ML',exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
test('mobile worklist, search and preview upload are honest and usable',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(url+'/?preview=1');
 await page.getByRole('textbox',{name:'Search invoices'}).fill('Botanica');
 await expect(page.locator('tbody tr')).toHaveCount(2);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/worklist-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Upload invoices',exact:true}).first().click();
 await expect(page.getByText('This interactive preview uses fictional invoices.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Toggle navigation'}).click();
 await page.getByRole('button',{name:'Item master',exact:true}).click();
 await expect(page.getByRole('heading',{name:'RMS item master.'})).toBeVisible();
});
test('live upload imports master, processes CSV, approves and downloads XLSX',async({page})=>{
 test.skip(!process.env.LIVE_URL,'Set LIVE_URL to the running local application');
 const live=process.env.LIVE_URL!;const number='UI-'+Date.now();await page.goto(live);
 await expect(page.getByText('Server connected')).toBeVisible();
 await page.getByRole('button',{name:'Brand setup',exact:true}).click();
 await expect(page.getByRole('checkbox',{name:'Include UPC in target workbook',exact:true})).not.toBeChecked();
 await page.getByLabel('Brand name',{exact:true}).fill('Synthetic training brand');
 await page.getByLabel('Default location',{exact:true}).fill('0001');
 await page.getByLabel('Location type',{exact:true}).fill('S');
 await page.getByRole('button',{name:'Add supplier rule'}).click();
 await page.getByLabel('Supplier rule 1 supplier id',{exact:true}).fill('SUP-1042');
 await page.getByLabel('Supplier rule 1 supplier site',{exact:true}).fill('UAE-01');
 await page.getByLabel('Supplier rule 1 tax code',{exact:true}).fill('VAT5');
 await page.getByRole('button',{name:'Save brand settings'}).click();
 await expect(page.getByText('Brand settings saved.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Item master',exact:true}).click();
 await page.getByRole('button',{name:'Import master',exact:true}).click();
 await page.locator('.file-input-button input').setInputFiles(path.resolve('public/templates/rms-item-master.csv'));
 await expect(page.getByText(/2 items imported/)).toBeVisible();await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('navigation').getByRole('button',{name:/^Invoices(?: \d+)?$/}).click();
 await page.getByRole('button',{name:'Upload invoices',exact:true}).first().click();
 await page.locator('.dropzone input[type=file]').first().setInputFiles({name:number+'.csv',mimeType:'text/csv',buffer:Buffer.from(readFileSync('public/templates/invoice.csv','utf8').replaceAll('SAMPLE-001',number))});
 await page.getByRole('button',{name:'Start upload'}).click();
 await expect(page.getByText('Saved to processing queue')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('textbox',{name:'Search invoices'}).fill(number);
 await expect(page.getByRole('button',{name:'Review '+number})).toBeVisible({timeout:20000});
 const exceptionDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download exceptions',exact:true}).click();
 const exceptionFile=await exceptionDownload;await exceptionFile.saveAs('test-results/live-exceptions.csv');
 expect(readFileSync('test-results/live-exceptions.csv','utf8')).toContain(number);
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await expect(page.getByRole('button',{name:'Download exceptions',exact:true})).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Review '+number}).click();
 await expect(page.getByRole('heading',{name:number,exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Document type',exact:true}).selectOption('invoice');
 await page.getByRole('button',{name:'Save changes'}).click();
 await expect(page.getByText('Amounts and item mappings reconcile')).toBeVisible();
 await page.getByRole('button',{name:'Audit trail'}).click();await expect(page.getByText('extraction completed',{exact:true})).toBeVisible();await expect(page.getByText('uploaded',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Approve invoice',exact:true}).click();await page.getByRole('button',{name:'Confirm review & approve'}).click();
 await expect(page.getByRole('button',{name:'Approved',exact:true})).toBeDisabled();await page.getByRole('button',{name:'All invoices',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select '+number,exact:true}).check();await page.getByRole('button',{name:'Export selected'}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download workbook'}).click();const file=await download;expect(file.suggestedFilename()).toMatch(/\.xlsx$/);await file.saveAs('test-results/live-export.xlsx');
});
