import type {Invoice,Line,Stats,CatalogItem,Alias,Audit,ExportRun,BrandSettings,ExceptionQueue,ExceptionGroup,Kpis,CatalogImport,ConversionRate,PolicyAudit} from './types';
import {REASON_CODES,REGISTRY} from './reasonCodes';
import {loadDemo,saveDemo,catalog,resetDemo} from './demo';
export let isPreview=false;
export const sourceRepository='https://github.com/muttonkodibiriyani/supplychain_studio';
export const downloadsRestricted=window.origin==='null';
export let health:{ocr_available?:boolean;supported_formats?:string[];status?:string}={};
const apiRoot=new URL('./api/',window.location.href.split('?')[0].split('#')[0]).href;
export function sourceUrl(id:string){return `${apiRoot}invoices/${encodeURIComponent(id)}/source`;}
function errorText(d:unknown):string {
 if(typeof d==='string')return d;
 if(Array.isArray(d))return d.map(errorText).join(' · ');
 if(d&&typeof d==='object'){const o=d as Record<string,unknown>;if(o.errors)return errorText(o.errors);if(o.message)return errorText(o.message);if(o.msg)return errorText(o.msg);if(o.detail)return errorText(o.detail);return JSON.stringify(d);}
 return 'The request could not be completed.';
}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{
 const r=await fetch(apiRoot+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});
 if(!r.ok){let d;try{d=await r.json();}catch{d=r.statusText;}throw new Error(errorText(d));}
 return r.json() as Promise<T>;
}
export async function initialize(){
 if(new URLSearchParams(location.search).get('preview')==='1'||import.meta.env.VITE_PREVIEW_MODE==='true'){isPreview=true;return;}
 try{const r=await fetch(apiRoot+'health',{signal:AbortSignal.timeout(3500)});if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw new Error();health=await r.json();isPreview=false;}catch{throw new Error('The invoice service could not be reached. Start the application server, then try again.');}
}
export async function stats():Promise<Stats>{if(!isPreview)return request('stats');const d=loadDemo();const s:Stats={total:d.invoices.length,queued:0,processing:0,needs_review:0,ready:0,exported:0,failed:0,matched_lines:0,total_lines:0,catalog_items:catalog.length,alias_count:d.aliases.length};for(const i of d.invoices){s[i.status]++;s.total_lines+=i.lines.length;s.matched_lines+=i.lines.filter(l=>l.rms_item_id).length;}return s;}
export async function invoices(status='',search='',offset=0,limit=25):Promise<{items:Invoice[];total:number}>{if(!isPreview)return request(`invoices?status=${encodeURIComponent(status)}&search=${encodeURIComponent(search)}&offset=${offset}&limit=${limit}`);const list=loadDemo().invoices.filter(i=>(!status||i.status===status)&&`${i.supplier_name} ${i.filename} ${i.invoice_number}`.toLowerCase().includes(search.toLowerCase()));return {items:list.slice(offset,offset+limit),total:list.length};}
export async function invoice(id:string):Promise<Invoice>{if(!isPreview)return request(`invoices/${id}`);const d=loadDemo().invoices.find(i=>i.id===id);if(!d)throw new Error('Invoice not found');return structuredClone(d);}
export async function saveInvoice(value:Invoice):Promise<Invoice>{
 if(!isPreview){const fields=['supplier_id','supplier_name','supplier_site','invoice_number','invoice_date','po_number','currency','subtotal','tax_total','total','document','document_type','location','location_type','tax_code','lines'];const body:Record<string,unknown>={expected_version:value.version};for(const k of fields)body[k]=value[k as keyof Invoice];return request(`invoices/${value.id}`,{method:'PUT',body:JSON.stringify(body)});}
 const d=loadDemo();const current=d.invoices.find(i=>i.id===value.id)!;if(current.version!==value.version)throw new Error('This invoice changed. Reopen it to load the latest version.');const updated={...value,version:value.version+1,status:'needs_review' as const,updated_at:new Date().toISOString()};d.invoices=d.invoices.map(i=>i.id===value.id?updated:i);d.audit[value.id]=[...(d.audit[value.id]||[]),{action:'Invoice corrected',created_at:updated.updated_at,details:'Changes saved in preview.'}];for(const line of value.lines.filter(l=>l.match_status==='confirmed'&&l.rms_item_id)){const old=d.aliases.find(a=>a.supplier_id===value.supplier_id&&a.description===line.description);if(old)old.rms_item_id=line.rms_item_id!;else d.aliases.push({supplier_id:value.supplier_id,description:line.description,rms_item_id:line.rms_item_id!});}saveDemo(d);return updated;
}
export function validation(i:Invoice):string[]{const e:string[]=[];if(!isPreview){if(i.document_type!=='invoice')e.push('Classify this document as an invoice only after reviewing the source');for(const [key,label] of [['location','Target location'],['location_type','Location type'],['tax_code','Tax code'],['supplier_site','Supplier site']] as const)if(!i[key])e.push(`${label} is required for the target workbook`);} for(const k of ['supplier_id','supplier_name','invoice_number','invoice_date','currency'] as const)if(!i[k])e.push(`${k.replaceAll('_',' ')} is required`);if(!i.lines.length)e.push('At least one invoice line is required');if(i.lines.some(l=>!l.rms_item_id))e.push('Resolve every item to an RMS item ID');if(i.lines.some(l=>!(Number(l.quantity)>0)||l.unit_price==null||l.line_total==null||Number(l.unit_price)<0||Number(l.line_total)<0))e.push('Check quantities and line amounts');if(i.lines.some(l=>l.quantity!=null&&l.unit_price!=null&&l.line_total!=null&&Math.abs(l.quantity*l.unit_price-l.line_total)>.010001))e.push('Quantity × unit price must equal each line total');if([i.subtotal,i.tax_total,i.total].some(v=>v==null||Number(v)<0))e.push('Subtotal, tax and total are required');if(i.subtotal!=null&&Math.abs(i.lines.reduce((s,l)=>s+Number(l.line_total||0),0)-i.subtotal)>.010001)e.push('Line totals must reconcile to the subtotal');if(i.total!=null&&i.subtotal!=null&&i.tax_total!=null&&Math.abs(i.subtotal+i.tax_total-i.total)>.010001)e.push('Subtotal + tax must equal the invoice total');return e;}
export async function approve(i:Invoice,acknowledgeTargetCostVariance=false):Promise<Invoice>{if(!isPreview)return request(`invoices/${i.id}/approve`,{method:'POST',body:JSON.stringify({expected_version:i.version,acknowledge_target_cost_variance:acknowledgeTargetCostVariance})});const errors=validation(i);if(errors.length)throw new Error(errors.join(' · '));const d=loadDemo();const updated={...i,status:'ready' as const,version:i.version+1};d.invoices=d.invoices.map(v=>v.id===i.id?updated:v);d.audit[i.id]=[...(d.audit[i.id]||[]),{action:'Approved for export',created_at:new Date().toISOString()}];saveDemo(d);return updated;}
export async function retry(id:string){if(isPreview)throw new Error('Run the server to process documents.');return request<Invoice>(`invoices/${id}/retry`,{method:'POST'});}
export async function getCatalog(search='',limit=100,supplierId=''):Promise<{items:CatalogItem[];total:number}>{if(!isPreview)return request(`catalog?search=${encodeURIComponent(search)}&limit=${limit}&supplier_id=${encodeURIComponent(supplierId)}`);const items=catalog.filter(c=>(!supplierId||!c.supplier_id||c.supplier_id===supplierId)&&`${c.description} ${c.rms_item_id}`.toLowerCase().includes(search.toLowerCase()));return {items:items.slice(0,limit),total:items.length};}
export async function aliases():Promise<{items:Alias[];total:number}>{if(!isPreview)return request('aliases');const d=loadDemo();return {items:d.aliases,total:d.aliases.length};}
export async function audit(id:string):Promise<{items:Audit[]}>{if(!isPreview)return request(`invoices/${id}/audit`);return {items:[{action:'Document captured',created_at:'2026-09-24T10:42:00Z',details:'Fictional sample invoice loaded.'},{action:'Items matched against RMS master',created_at:'2026-09-24T10:42:02Z'},...(loadDemo().audit[id]||[])]};}
const ADJUSTMENT_WORDS=['discount','rebate','credit','allowance','adjustment','surcharge','promotion','promo','rounding'];
function isAdjustmentLine(l:Line):boolean{const d=(l.description||'').toLowerCase();return ADJUSTMENT_WORDS.some(w=>new RegExp('\\b'+w).test(d));}
function previewPriceCode(l:Line):string|null{return (l.target_cost_comparison_status||'')==='above_tolerance'?'price_above_tolerance':null;}
function previewReasonCodes(i:Invoice):string[]{const codes=new Set<string>();if(i.status==='queued'||i.status==='processing')return [];if(i.status==='failed')return ['extraction_failed'];if(i.status==='ready'||i.status==='exported')return [];for(const k of ['supplier_id','invoice_number','invoice_date','currency'] as const)if(!i[k])codes.add(k==='supplier_id'?'supplier_unresolved':'header_field_missing');if(!i.supplier_name)codes.add('supplier_unresolved');for(const l of i.lines){if(!l.rms_item_id)codes.add(l.match_status==='suggested'?'line_low_confidence':isAdjustmentLine(l)?'adjustment_unpaired':'line_unmapped');const price=previewPriceCode(l);if(price)codes.add(price);}if(i.lines.some(l=>l.quantity!=null&&l.unit_price!=null&&l.line_total!=null&&Math.abs(l.quantity*l.unit_price-l.line_total)>.010001)||(i.total!=null&&i.subtotal!=null&&i.tax_total!=null&&Math.abs(i.subtotal+i.tax_total-i.total)>.010001))codes.add('total_reconciliation_failed');return REASON_CODES.map(e=>e.code).filter(c=>codes.has(c));}
export async function exceptions():Promise<ExceptionQueue>{if(!isPreview)return request('exceptions');const d=loadDemo();const now=Date.now();const groups:Record<string,ExceptionGroup>={};let withCodes=0;for(const i of d.invoices){const codes=previewReasonCodes(i);if(!codes.length)continue;withCodes++;const age=Math.max(0,Math.round((now-new Date(i.created_at).getTime())/1000));const summary={id:i.id,invoice_number:i.invoice_number,filename:i.filename,supplier_name:i.supplier_name,supplier_id:i.supplier_id,status:i.status,document_type:i.document_type||null,created_at:i.created_at,age_seconds:age,reason_codes:codes,duplicate_of:[]};for(const code of codes){const entry=REGISTRY[code];const g=groups[code]||(groups[code]={code,owner:entry.owner,message:entry.message,level:entry.level,count:0,oldest_age_seconds:null,oldest_invoice_id:null,invoices:[],truncated:false});g.count++;if(g.oldest_age_seconds==null||age>g.oldest_age_seconds){g.oldest_age_seconds=age;g.oldest_invoice_id=i.id;}g.invoices.push(summary);}}const ordered=Object.values(groups).sort((a,b)=>b.count-a.count||a.code.localeCompare(b.code));for(const g of ordered)g.invoices.sort((a,b)=>(b.age_seconds||0)-(a.age_seconds||0));return {as_of:new Date().toISOString(),invoices_total:d.invoices.length,invoices_with_exceptions:withCodes,groups:ordered,registry:REASON_CODES};}
export async function kpis():Promise<Kpis>{if(!isPreview)return request('kpis');const d=loadDemo();let touchless=0,firstTime=0;const cycles:number[]=[];for(const i of d.invoices){const trail=d.audit[i.id]||[];const done=i.status==='ready'||i.status==='exported';if(done&&!trail.some(a=>a.action==='Invoice corrected'))touchless++;if(i.lines.length&&i.lines.every(l=>l.match_status==='auto'&&l.rms_item_id))firstTime++;const approved=trail.find(a=>a.action==='Approved for export');if(done&&approved?.created_at){const s=(new Date(approved.created_at).getTime()-new Date(i.created_at).getTime())/1000;if(Number.isFinite(s))cycles.push(Math.max(0,s));}}cycles.sort((a,b)=>a-b);const m=cycles.length?cycles.length%2?cycles[(cycles.length-1)/2]:(cycles[cycles.length/2-1]+cycles[cycles.length/2])/2:null;const approvalStage=d.invoices.filter(i=>i.status==='ready'||i.status==='exported').length;return {as_of:new Date().toISOString(),contains_demo_data:true,k1_touchless:{numerator:touchless,denominator:d.invoices.length,approval_stage:approvalStage,evaluable:approvalStage>0,not_evaluable_reason:approvalStage>0?null:'no invoice has reached ready or exported in this workspace, so no touchless outcome can be observed yet',definition:'invoices in ready or exported whose audit trail has no human action other than the approval itself, over all invoices'},k2_first_time_match:{numerator:firstTime,denominator:d.invoices.length,definition:'invoices whose lines all matched automatically at the first extraction, over invoices that completed extraction'},k3_cycle_time:{median_seconds:m,n:cycles.length,evaluable:cycles.length>0,not_evaluable_reason:cycles.length>0?null:'no invoice has reached ready in this workspace, so there is no cycle to measure',definition:'median seconds from upload to the first transition into ready, over invoices that ever reached ready (preview: approvals made in this session)'}};}
export async function exportRuns():Promise<{items:ExportRun[]}>{if(!isPreview)return request('exports');return {items:loadDemo().exports};}
export function download(blob:Blob,filename:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export async function downloadExceptions(){
 if(isPreview)throw new Error('Run the application to download your exception report.');
 const response=await fetch(apiRoot+'reports/exceptions.csv');
 if(!response.ok)throw new Error(errorText(await response.json()));
 download(await response.blob(),`invoice-exceptions-${new Date().toISOString().slice(0,10)}.csv`);
 return Number(response.headers.get('X-Exception-Count')||0);
}
export async function downloadSource(){const response=await fetch('./source-package.json');if(!response.ok)throw new Error('Source download is unavailable. Use the ZIP attached to the tm8 task.');const data=await response.json();const bytes=Uint8Array.from(atob(data.base64),(c:string)=>c.charCodeAt(0));download(new Blob([bytes],{type:'application/zip'}),data.filename||'invoice-studio-source.zip');}
export async function exportInvoices(ids:string[]){
 if(!isPreview){const r=await fetch(apiRoot+'exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoice_ids:ids})});if(!r.ok){throw new Error(errorText(await r.json()));}download(await r.blob(),`invoice-review-${new Date().toISOString().slice(0,10)}.xlsx`);return;}
 const d=loadDemo();const selected=d.invoices.filter(i=>ids.includes(i.id));if(selected.some(i=>i.status!=='ready'))throw new Error('Only approved invoices can be exported.');const payload={schema:'invoice-studio.internal-review.v1',notice:'Fictional preview data. Not an approved REIM interface.',headers:selected.map(({lines,raw_text,...i})=>i),tax:selected.map(i=>({invoice_number:i.invoice_number,tax_total:i.tax_total,currency:i.currency})),details:selected.flatMap(i=>i.lines.map(l=>({invoice_number:i.invoice_number,...l})))};const text=JSON.stringify(payload,null,2);if(!downloadsRestricted)download(new Blob([text],{type:'application/json'}),'sample-invoice-review.json');d.exports.unshift({id:`EXP-${Date.now()}`,created_at:new Date().toISOString(),invoice_count:ids.length,line_count:selected.reduce((s,i)=>s+i.lines.length,0),filename:'sample-invoice-review.json',invoice_ids:ids});d.invoices=d.invoices.map(i=>ids.includes(i.id)?{...i,status:'exported',version:i.version+1}:i);saveDemo(d);return downloadsRestricted?text:undefined;
}
export async function upload(file:File,supplierId:string,supplierName:string){if(isPreview)throw new Error('This preview contains sample data. Start the application to upload real invoices.');const f=new FormData();f.append('files',file);if(supplierId)f.append('supplier_id',supplierId);if(supplierName)f.append('supplier_name',supplierName);return request<{accepted:{id:string;filename:string}[];duplicates:{id:string;filename:string}[];rejected:{filename:string;error:string}[]}>('invoices/upload',{method:'POST',body:f});}
export async function importCatalog(file:File,costCurrency='',declaredBy=''){if(isPreview)throw new Error('Start the application to import your RMS master.');const f=new FormData();f.append('file',file);if(costCurrency)f.append('cost_currency',costCurrency);if(declaredBy)f.append('declared_by',declaredBy);return request<{imported:number;skipped:number;warnings:string[];import:CatalogImport|null}>('catalog/import',{method:'POST',body:f});}
export async function getCatalogImports():Promise<{items:CatalogImport[]}>{if(isPreview)return {items:[]};return request('catalog/imports');}
export async function declareImportCurrency(importId:string,costCurrency:string,declaredBy:string):Promise<CatalogImport>{if(isPreview)throw new Error('Start the application to declare a master cost currency.');return request(`catalog/imports/${encodeURIComponent(importId)}`,{method:'PUT',body:JSON.stringify({cost_currency:costCurrency,declared_by:declaredBy})});}
export async function getRates():Promise<{items:ConversionRate[]}>{if(isPreview)return {items:[]};return request('rates');}
export async function addRate(rate:{from_currency:string;to_currency:string;rate:string;source:string;entered_by:string;effective_date?:string}):Promise<ConversionRate>{if(isPreview)throw new Error('Start the application to enter conversion rates.');return request('rates',{method:'POST',body:JSON.stringify(rate)});}
export async function getPolicyAudit():Promise<{items:PolicyAudit[]}>{if(isPreview)return {items:[]};return request('settings/audit');}
export async function seedDemo(){if(isPreview){resetDemo();return;}await request('demo',{method:'POST'});}

export async function getSettings():Promise<BrandSettings>{if(isPreview)return {version:1,brand_label:'Sample brand',location:'001',location_type:'S',include_upc_in_export:false,supplier_rules:[],target_cost_policy:{mode:'invoice_only',maximum_absolute_difference_aed:10},tolerance_policy:{version:1,owner:'',effective_date:'2026-01-01',absolute_tolerance:10,percentage_tolerance:null,scope:'per_line',invoice_currency_scope:['AED']}};return request('settings');}
export async function saveSettings(value:BrandSettings):Promise<BrandSettings>{if(isPreview)throw new Error('Run the full application to configure a brand.');const {version,...fields}=value;return request('settings',{method:'PUT',body:JSON.stringify({...fields,expected_version:version})});}
export async function importAliases(file:File):Promise<{imported:number}>{if(isPreview)throw new Error('Run the full application to import reviewed matches.');const form=new FormData();form.append('file',file);return request('aliases/import',{method:'POST',body:form});}
