import {useEffect,useState} from 'react';
import {Plus,Save,Trash2,LoaderCircle,Building2,ShieldCheck} from 'lucide-react';
import * as api from './api';
import type {BrandSettings as Settings} from './types';

export default function BrandSettings({onSaved}:{onSaved:(label:string)=>void}){
 const [value,setValue]=useState<Settings|null>(null);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 useEffect(()=>{api.getSettings().then(setValue).catch(e=>setError(e.message));},[]);
 function patch(fields:Partial<Settings>){setValue(v=>v?{...v,...fields}:v);setSaved(false);}
 async function save(){if(!value)return;setBusy(true);setError('');try{const next=await api.saveSettings({...value,target_cost_policy:{...value.target_cost_policy,mode:'invoice_only'}});setValue(next);setSaved(true);onSaved(next.brand_label);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><div className="eyebrow">ONE BRAND · ONE ITEM MASTER</div><h1>Brand setup<span className="heading-dot">.</span></h1><p>Set the codes your receiving system requires before approving invoices.</p></div><button className="btn primary" onClick={save} disabled={!value||busy||api.isPreview}>{busy?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>} Save brand settings</button></div>
 {error&&<p className="error-banner" role="alert">{error}</p>}{saved&&<p className="success-banner" role="status">Brand settings saved. Review invoice target fields before approval.</p>}
 {api.isPreview&&<p className="inline-note">These are illustrative settings. Run the full application to configure your brand and import its own master.</p>}
 {!value&&!error&&<LoaderCircle className="spin"/>}
 {value&&<fieldset className="brand-settings" disabled={busy||api.isPreview}><section className="panel guide-card"><div className="section-heading"><div><h2><Building2 size={20}/> Workspace and location</h2><p>Codes remain text, including leading zeroes. Use the actual target-system values.</p></div></div><div className="fields-grid"><label className="field-wide">Brand name<input value={value.brand_label} onChange={e=>patch({brand_label:e.target.value})} placeholder="Your brand name"/></label><label>Default location<input value={value.location} onChange={e=>patch({location:e.target.value})} placeholder="Target location code"/></label><label>Location type<input value={value.location_type} onChange={e=>patch({location_type:e.target.value})} placeholder="e.g. S for your configured store type"/></label></div><p className="muted">Use a different Compose project and data volume for another brand. That keeps its invoices, catalog and learned matches separate.</p></section>
 <section className="panel guide-card"><div className="section-heading"><div><h2>Supplier site and tax codes</h2><p>Match each exact supplier ID in the item master to its accepted upload codes.</p></div><button className="btn small" onClick={()=>patch({supplier_rules:[...value.supplier_rules,{supplier_id:'',supplier_site:'',tax_code:''}]})}><Plus size={16}/> Add supplier rule</button></div><div className="table-scroll"><table><thead><tr><th>Supplier ID</th><th>Supplier site</th><th>Tax code</th><th/></tr></thead><tbody>{value.supplier_rules.map((rule,index)=><tr key={index}>{(['supplier_id','supplier_site','tax_code'] as const).map(field=><td key={field}><input aria-label={`Supplier rule ${index+1} ${field.replaceAll('_',' ')}`} value={rule[field]} onChange={e=>patch({supplier_rules:value.supplier_rules.map((row,i)=>i===index?{...row,[field]:e.target.value}:row)})}/></td>)}<td><button className="icon-btn" aria-label={`Remove supplier rule ${index+1}`} onClick={()=>patch({supplier_rules:value.supplier_rules.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>{!value.supplier_rules.length&&<p className="muted">No supplier defaults configured. Missing codes must be resolved during review.</p>}</section>
 <section className="panel guide-card"><h2>Invoice cost and RMS comparison</h2><p>The target workbook always uses the invoice net unit cost after discount. RMS costs help identify differences for review and never replace the invoice cost.</p><div className="fields-grid"><label>Target unit cost<input readOnly value="Invoice net unit cost after discount"/></label><label>RMS variance review threshold (AED)<input type="number" min="0" step="0.01" value={value.target_cost_policy.maximum_absolute_difference_aed} onChange={e=>patch({target_cost_policy:{...value.target_cost_policy,mode:'invoice_only',maximum_absolute_difference_aed:Number(e.target.value)}})}/></label></div><div className="inline-note"><ShieldCheck size={18}/><span>Review differences above this threshold before approval. The exported detail amounts must reconcile with the invoice subtotal.</span></div></section><section className="panel guide-card"><h2>Target workbook UPC</h2><label><input type="checkbox" checked={value.include_upc_in_export??false} onChange={e=>patch({include_upc_in_export:e.target.checked})}/> Include UPC in target workbook</label><p>Leave this off to keep the UPC column blank, as in the reviewed target examples. Enable it only after your receiving system confirms it accepts catalog UPCs. Barcode matching still works when this is off.</p></section></fieldset>}
 </>;
}
