import {useEffect,useRef,type ReactNode} from 'react';
import {X,Check,Clock3,AlertCircle,LoaderCircle,ArrowUpRight,FileCheck2} from 'lucide-react';
import type {Status} from './types';
export const statusLabels:Record<Status,string>={queued:'Queued',processing:'Processing',needs_review:'Needs review',ready:'Ready to export',exported:'Exported',failed:'Processing failed'};
export function StatusBadge({status}:{status:Status}){const Icon=status==='ready'?Check:status==='exported'?ArrowUpRight:status==='processing'?LoaderCircle:status==='queued'?Clock3:AlertCircle;return <span className={`status status-${status}`}><Icon size={13}/>{statusLabels[status]||status}</span>;}
export function Empty({title,children,icon}:{title:string;children:ReactNode;icon?:ReactNode}){return <div className="empty">{icon||<FileCheck2 size={32}/>}<h3>{title}</h3><div>{children}</div></div>;}
export function Money({value,currency='AED'}:{value:number|null|undefined;currency?:string}){return <span className="money">{value==null?'—':<><span>{currency} </span>{Number(value).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}</>}</span>;}
export function Dialog({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;ref.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const f=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select,textarea,a[href],[tabindex="0"]');if(!f?.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;prev?.focus();};},[onClose]);
 return <div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={`dialog ${wide?'dialog-wide':''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><div className="dialog-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</div></div>;
}
export function dateLabel(s:string){if(!s)return '—';const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}
