export type Status = 'queued'|'processing'|'needs_review'|'ready'|'exported'|'failed';
export type Candidate = {catalog_item_id?:string;rms_parent_item?:string;uom?:string;rms_upc?:string;rms_unit_cost?:number|null;rms_item_id:string;description:string;score:number;reason:string};
export type Line = {catalog_item_id?:string|null;rms_parent_item?:string;rms_upc?:string;rms_unit_cost?:number|null;rms_cost_currency?:string|null;rms_unit_cost_converted?:number|null;conversion_rate_id?:number|null;target_cost_comparison_status?:string|null;target_cost_comparison_reason?:string|null;target_unit_cost?:number|null;target_cost_source?:string;target_cost_variance?:number|null;target_cost_review_required?:boolean;id:string;description:string;quantity:number|null;unit_price:number|null;line_total:number|null;tax_rate?:number|null;uom:string;rms_item_id:string|null;match_status:'unmatched'|'suggested'|'auto'|'confirmed';confidence:number;candidates:Candidate[]};
export type Invoice = {document?:string;document_type?:string;location?:string;location_type?:string;tax_code?:string;target_cost_reviewed?:boolean;target_total_ex_tax?:number|null;target_cost_variance?:number|null;target_cost_review_required?:boolean;id:string;filename:string;supplier_id:string;supplier_name:string;supplier_site:string;invoice_number:string;invoice_date:string;po_number:string;currency:string;subtotal:number|null;tax_total:number|null;total:number|null;status:Status;extraction_method:string;created_at:string;updated_at:string;error:string|null;warnings:string[];version:number;pages:number;lines:Line[];raw_text:string;line_count?:number;matched_lines?:number};
export type CatalogItem = {catalog_item_id?:string;rms_parent_item?:string;upc?:string;rms_item_id:string;description:string;supplier_id?:string;uom:string;unit_cost?:number;cost_currency?:string|null};
export type TolerancePolicy = {version:number;owner:string;effective_date:string;absolute_tolerance:number;percentage_tolerance:number|null;scope:'per_line'|'per_invoice';invoice_currency_scope:string[]};
export type PolicyAudit = {id:number;policy_name:string;actor:string;changed_at:string;settings_version:number|null;before:unknown;after:unknown};
export type CatalogImport = {id:string;filename:string;imported_at:string;imported_rows:number;skipped_rows:number;cost_currency:string|null;cost_currency_source:string|null;declared_by:string|null;declared_at:string|null;undeclared_currency_rows:number};
export type ConversionRate = {id:number;from_currency:string;to_currency:string;rate:number;source:string;entered_by:string;entered_at:string;effective_date:string};
export type Stats = {total:number;queued:number;processing:number;needs_review:number;ready:number;exported:number;failed:number;matched_lines:number;total_lines:number;catalog_items:number;alias_count:number};
export type Audit = {id?:string;action?:string;event_type?:string;event?:string;created_at?:string;timestamp?:string;details?:unknown;actor?:string};
export type Alias = {supplier_id:string;description?:string;normalized_description?:string;rms_item_id:string;created_at?:string};
export type ExportRun = {id:string;created_at:string;invoice_count?:number;line_count?:number;filename?:string;invoice_ids?:string[]};

export type BrandSettings = {version:number;brand_label:string;location:string;location_type:string;include_upc_in_export:boolean;supplier_rules:{supplier_id:string;supplier_site:string;tax_code:string}[];target_cost_policy:{mode:string;maximum_absolute_difference_aed:number};tolerance_policy:TolerancePolicy;changed_by?:string};
