import {useState,useRef,useCallback} from 'react';
import {UploadCloud,FolderOpen,FileUp,CheckCircle2,AlertCircle,Copy,ArrowRight,Download,LoaderCircle} from 'lucide-react';
import * as api from './api';
import {Dialog} from './components';
type UploadItem={file:File;state:'waiting'|'uploading'|'accepted'|'duplicate'|'failed';message?:string};
export default function Upload({onClose,onDone,onGuide}:{onClose:()=>void;onDone:()=>void;onGuide:()=>void}){
 const [items,setItems]=useState<UploadItem[]>([]);const [supplierId,setSupplierId]=useState('');const [supplierName,setSupplierName]=useState('');const [busy,setBusy]=useState(false);const [drag,setDrag]=useState(false);const [paused,setPaused]=useState(false);const stop=useRef(false);const files=useRef<HTMLInputElement>(null);const folder=useRef<HTMLInputElement>(null);const counts=items.reduce((a,i)=>({...a,[i.state]:(a[i.state]||0)+1}),{} as Record<string,number>);
 const close=useCallback(()=>{if(busy){setPaused(true);stop.current=true;}else onClose();},[busy,onClose]);
 function add(list:FileList|File[]|null){if(!list||busy)return;setItems(old=>[...old,...Array.from(list).map(file=>({file,state:'waiting' as const}))]);}
 async function start(){if(api.isPreview)return;setBusy(true);setPaused(false);stop.current=false;const pending=items.map((item,index)=>({item,index})).filter(x=>x.item.state==='waiting'||x.item.state==='failed');let next=0;const update=(index:number,state:UploadItem['state'],message?:string)=>setItems(old=>old.map((v,i)=>i===index?{...v,state,message}:v));
 const worker=async()=>{while(next<pending.length&&!stop.current){const {item,index}=pending[next++];update(index,'uploading');try{const r=await api.upload(item.file,supplierId,supplierName);if(r.rejected?.length)update(index,'failed',r.rejected[0].error);else if(r.duplicates?.length)update(index,'duplicate','Already in your worklist');else if(r.accepted?.length)update(index,'accepted','Saved to processing queue');else update(index,'failed','Server did not acknowledge this file');}catch(e){update(index,'failed',(e as Error).message);}}};await Promise.all([worker(),worker(),worker()]);setBusy(false);onDone();}
 const completed=(counts.accepted||0)+(counts.duplicate||0)+(counts.failed||0);return <Dialog title="Upload invoices" subtitle="Add a batch. We’ll capture the details and match your items." onClose={close} wide>
 {api.isPreview?<div className="preview-upload"><div className="round-icon"><UploadCloud size={30}/></div><h3>Ready to work with your invoices</h3><p>This interactive preview uses fictional invoices. The full application processes your documents on your own server.</p><div className="format-chips"><span>PDF</span><span>JPG / PNG</span><span>TIFF / WebP</span><span>CSV / XLSX</span><span>DOCX / TXT</span></div>{api.downloadsRestricted?<p className="inline-note">Download the final source ZIP from this task’s attachments to run the full application.</p>:<a className="btn primary" href={api.sourceRepository} target="_blank" rel="noreferrer"><Download size={17}/> Get source on GitHub</a>}<button className="text-btn" onClick={()=>{onClose();onGuide();}}>View setup and supported formats <ArrowRight size={16}/></button><small>Includes durable queue, native OCR, source files, tests and Docker setup.</small></div>:<>
 <div className="upload-meta"><label>Supplier ID <span>optional at upload</span><input placeholder="e.g. SUP-1042" value={supplierId} onChange={e=>setSupplierId(e.target.value)} disabled={busy}/></label><label>Supplier name <span>for this batch</span><input placeholder="Use one supplier per batch if specified" value={supplierName} onChange={e=>setSupplierName(e.target.value)} disabled={busy}/></label></div>
 <div className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add(e.dataTransfer.files);}}><div className="round-icon"><UploadCloud size={27}/></div><h3>Drop your invoices here</h3><p>Select thousands of files. Only three uploads run at a time.</p><div className="button-row"><button className="btn primary" disabled={busy} onClick={()=>files.current?.click()}><FileUp size={16}/> Browse files</button><button className="btn" disabled={busy} onClick={()=>folder.current?.click()}><FolderOpen size={16}/> Choose a folder</button></div><small>PDF, JPG, PNG, TIFF, WebP, BMP, CSV, XLSX, DOCX and TXT</small><input ref={files} type="file" multiple hidden onChange={e=>{add(e.target.files);e.target.value='';}}/><input ref={folder} type="file" multiple hidden {...{webkitdirectory:''}} onChange={e=>{add(e.target.files);e.target.value='';}}/></div>
 <p className="upload-note">One invoice per file; multi-page invoices are supported. Accepted files stay in the server queue if you close this window. Keep this page open until the remaining files finish uploading.</p>
 {!!items.length&&<div className="upload-results"><div className="section-heading"><strong>{items.length.toLocaleString()} files selected</strong><span>{completed.toLocaleString()} uploaded or checked</span></div><div className="progress-track"><i style={{width:`${completed/items.length*100}%`}}/></div><div className="upload-counts"><span><CheckCircle2 size={14}/>{counts.accepted||0} accepted</span><span><Copy size={14}/>{counts.duplicate||0} duplicates</span><span><AlertCircle size={14}/>{counts.failed||0} failed</span></div><div className="upload-files">{items.filter(i=>i.state==='failed'||i.state==='uploading').concat(items.filter(i=>!['failed','uploading'].includes(i.state))).slice(0,30).map((item,index)=><div key={index}><span title={item.file.name}>{item.file.name}</span><span className={item.state==='failed'?'danger-text':'muted'} title={item.message}>{item.state==='uploading'?<LoaderCircle className="spin" size={14}/>:item.message||item.state}</span></div>)}{items.length>30&&<small>Showing up to 30 files; counts include the entire batch.</small>}</div></div>}
 <div className="dialog-footer"><span>{paused?'Paused. Accepted files will keep processing.':'Documents are stored on your server.'}</span><div className="button-row">{busy?<button className="btn" onClick={()=>{stop.current=true;setPaused(true);}}>Pause uploads</button>:<button className="btn" onClick={onClose}>Close</button>}<button className="btn primary" disabled={busy||!items.some(i=>i.state==='waiting'||i.state==='failed')} onClick={start}>{busy?<LoaderCircle className="spin" size={16}/>:<UploadCloud size={16}/>} {busy?'Uploading…':counts.failed?'Upload remaining / retry':'Start upload'}</button></div></div></>}
 </Dialog>;
}
